{{- if .Values.istio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "acmeair.fullname" . }}-customer-db-ibmi
  labels:
    {{- include "acmeair.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    name: {{ include "acmeair.fullname" . }}-customer-db-ibmi
{{-end }}