{{- if not .Values.istio.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: jenkins
spec:
  #host: {{ include "acmeair.fullname" . }}.apps.ocp4.demointel.mpl
  host: {{ .Values.host }}  
  to:
    kind: Service
    name: jenkins
    weight: 100
  wildcardPolicy: None
{{- end }}