apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acmeair-jmeter
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi