apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: acmeair-jmeter
  name: acmeair-jmeter
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: acmeair-jmeter:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy: {}
    type: Docker
  successfulBuildsHistoryLimit: 5
